name: fruits_hub
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  svg_flutter: ^0.0.1
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  get_it: ^8.0.3
  modal_progress_hud_nsn: ^0.5.1
  top_snackbar_flutter: ^3.2.0
  shared_preferences: ^2.5.2
  dots_indicator: ^4.0.1
  supabase_flutter: ^2.8.3
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  carousel_slider: ^5.0.0
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/vuesax/bold/
    - assets/images/vuesax/outline/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: app_images.dart
  field_prefix: null
