// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk6BIuYFTDcbSrouTjhG8k4oB9EYg10qg',
    appId: '1:814891868381:web:a9ddbe6fac017a23affb34',
    messagingSenderId: '814891868381',
    projectId: 'fruirs-hub',
    authDomain: 'fruirs-hub.firebaseapp.com',
    storageBucket: 'fruirs-hub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsL3cVVbBx_eGkcQPJHOs5p7aiBNzMqTk',
    appId: '1:814891868381:android:578f6915e7667717affb34',
    messagingSenderId: '814891868381',
    projectId: 'fruirs-hub',
    storageBucket: 'fruirs-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWceoqrXUC4StuNIK0lO5K-r5_aNwqErs',
    appId: '1:814891868381:ios:53c12b3f7abf4a3eaffb34',
    messagingSenderId: '814891868381',
    projectId: 'fruirs-hub',
    storageBucket: 'fruirs-hub.firebasestorage.app',
    iosBundleId: 'com.yousef.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWceoqrXUC4StuNIK0lO5K-r5_aNwqErs',
    appId: '1:814891868381:ios:53c12b3f7abf4a3eaffb34',
    messagingSenderId: '814891868381',
    projectId: 'fruirs-hub',
    storageBucket: 'fruirs-hub.firebasestorage.app',
    iosBundleId: 'com.yousef.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk6BIuYFTDcbSrouTjhG8k4oB9EYg10qg',
    appId: '1:814891868381:web:b77bf472aa80fc81affb34',
    messagingSenderId: '814891868381',
    projectId: 'fruirs-hub',
    authDomain: 'fruirs-hub.firebaseapp.com',
    storageBucket: 'fruirs-hub.firebasestorage.app',
  );
}
